package Day4;
//1. Assume that a bank offers two types of accounts: standard and premium, from which a
//customer can select one while opening a bank account. An account holder can deposit any
//amount ofmoney into his or her account, but when withdrawing, a premium account holder can
//withdraw up to Rs 10 lakh in a day, whilst a regular account holder can withdraw up to Rs I lakh
//free of charge and up to Rs 5 lakh with a .05% penalty. In this regard write ajava program with
//the following specifi cations:
//i. Create a super class Account that contains various information of a accomt holder like
//        account number, account type, name, current balance etc. along with day, month and year
//of last deposit. Account class also contains three methods: one for checking current
//balance, one for depositing money and the third for withdrawing money. New account is
//created with the personal information in the constructor of the class and the account
//        number is generated by auto-increment.
//ii. Create two subclasses: StandardAccount and hemiumAccoun! both inherit the members
//of the Account class and override the withdrawal0 method as per above mentioned
//        specifications.
//iii. In main0 method, create some account instances for both the account types and
//demonstrate the execution of the methods. Suitable transaction messages need to be
//displayed.
//
//Using Dynamic Method Dispatch concept display the methods of each class.
public class account {
}
