package Day4;
//1. Assume that a bank offers two types of accounts: standard and premium, from which a
//customer can select one while opening a bank account. An account holder can deposit any
//amount ofmoney into his or her account, but when withdrawing, a premium account holder can
//withdraw up to Rs 10 lakh in a day, whilst a regular account holder can withdraw up to Rs I lakh
//free of charge and up to Rs 5 lakh with a .05% penalty. In this regard write ajava program with
//the following specifi cations:
//i. Create a super class Account that contains various information of a accomt holder like
//        account number, account type, name, current balance etc. along with day, month and year
//of last deposit. Account class also contains three methods: one for checking current
//balance, one for depositing money and the third for withdrawing money. New account is
//created with the personal information in the constructor of the class and the account
//        number is generated by auto-increment.
//ii. Create two subclasses: StandardAccount and hemiumAccoun! both inherit the members
//of the Account class and override the withdrawal0 method as per above mentioned
//        specifications.
//iii. In main0 method, create some account instances for both the account types and
//demonstrate the execution of the methods. Suitable transaction messages need to be
//displayed.
//
//Using Dynamic Method Dispatch concept display the methods of each class.
class Account {
    protected int accountNumber;
    protected String name;
    protected String accountType;
    protected double balance;

    protected int day, month, year;

    private static int accCounter = 1000;   // auto-increment account number

    // Constructor
    public Account(String name, String accountType, double balance,
                   int day, int month, int year) {
        this.accountNumber = ++accCounter;
        this.name = name;
        this.accountType = accountType;
        this.balance = balance;
        this.day = day;
        this.month = month;
        this.year = year;

        System.out.println("\nAccount created successfully!");
        System.out.println("Account No: " + accountNumber);
    }

    // Method to check balance
    public void checkBalance() {
        System.out.println("Current Balance: Rs " + balance);
    }

    // Method to deposit money
    public void deposit(double amount, int d, int m, int y) {
        balance += amount;
        day = d;
        month = m;
        year = y;
        System.out.println("Deposited Rs " + amount);
        System.out.println("Deposit Date: " + day + "/" + month + "/" + year);
    }

    // Method to withdraw money (to be overridden)
    public void withdraw(double amount) {
        System.out.println("Withdrawal method of Account class");
    }
}
class StandardAccount extends Account {

    public StandardAccount(String name, double balance,
                           int day, int month, int year) {
        super(name, "Standard", balance, day, month, year);
    }

    // Overridden withdrawal method
    @Override
    public void withdraw(double amount) {
        if (amount <= 100000) {
            if (amount <= balance) {
                balance -= amount;
                System.out.println("Withdrawn Rs " + amount + " (No charge)");
            } else {
                System.out.println("Insufficient balance!");
            }
        } else if (amount <= 500000) {
            double penalty = amount * 0.0005; // 0.05%
            double total = amount + penalty;

            if (total <= balance) {
                balance -= total;
                System.out.println("Withdrawn Rs " + amount);
                System.out.println("Penalty charged: Rs " + penalty);
            } else {
                System.out.println("Insufficient balance including penalty!");
            }
        } else {
            System.out.println("Standard Account limit exceeded (Max Rs 5 lakh)");
        }
    }
}
class PremiumAccount extends Account {

    public PremiumAccount(String name, double balance,
                          int day, int month, int year) {
        super(name, "Premium", balance, day, month, year);
    }

    // Overridden withdrawal method
    @Override
    public void withdraw(double amount) {
        if (amount <= 1000000) {  // Rs 10 lakh
            if (amount <= balance) {
                balance -= amount;
                System.out.println("Withdrawn Rs " + amount + " (No penalty)");
            } else {
                System.out.println("Insufficient balance!");
            }
        } else {
            System.out.println("Premium Account limit exceeded (Max Rs 10 lakh)");
        }
    }
}
public class BankDemo {
    public static void main(String[] args) {

        // Dynamic Method Dispatch
        Account acc;

        acc = new StandardAccount("Manash", 800000, 1, 1, 2026);
        acc.checkBalance();
        acc.deposit(50000, 5, 1, 2026);
        acc.withdraw(200000);   // with penalty
        acc.checkBalance();

        System.out.println("--------------------------------");

        acc = new PremiumAccount("Rohit", 2000000, 2, 1, 2026);
        acc.checkBalance();
        acc.withdraw(900000);   // no penalty
        acc.checkBalance();
    }
}

